### ISSUE TITLE
Idea - namespace branch names

### ISSUE THREAD

**Issue by vsoch** [autamus/binoc#1]
It looks like the names of the branches are currently in the format `update-<package>` and I'd like to suggest that we provide a namespace for binoc, like `binoc/update-<package>` - that way we can ensure that only branches with prefix `binoc/*` are those that trigger a subsequent action. I'll use the prefix `update-` for now, and we can change this if the action gets it added.

**Comment by alecbcs** [comment]
Good idea! I'm thinking we could add this as a field in the config (e.g. `git_branch_prefix` or `git_branch_namespace`) then let people overwrite the default `binoc/` namespace? For `spacktainer-registry` maybe we want the prefix to be `packages/update-<package>` that way we can still have the build system run on user submitted pull requests as well (for updates that Binoc can't automatically handle)?

**Comment by vsoch** [comment]
`git_branch_prefix` is more intuitive than namespace, so my vote is for that! I might even say `pull_request_branch_prefix` or `pr_branch_prefix` so it's just blatantly obvious. And agree, I would do binoc as the default.

> packages/update-<package> that way we can still have the build system run on user submitted pull requests as well (for updates that Binoc can't automatically handle)?

I would say stick to binoc, as a PR opened by binoc should be labeled as such. To handle the case of having a user PR that we want to run tests for, what about adding an "on applying this label" trigger to run the tests? E.g., see that there is a "labeled" event here that we could then check and continue running given a particular label applied by a maintainer: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request

That way, a user can open a PR with any branch name and we can run the tests by applying the label.

**Comment by alecbcs** [comment]
> That way, a user can open a PR with any branch name and we can run the tests by applying the label.

Oh awesome! I like this way better! Do you know if we can apply labels to a PR after it has been opened?

**Comment by vsoch** [comment]
Oh definitely, I do it all the time :)

**Comment by alecbcs** [comment]
Added support for custom branch prefixes last night with the release of v0.0.5. The setting can be modified by using `branch_prefix: 'binoc/'` in the calling action.yml. By default Binoc uses `binoc/` as the prefix for all git branches it creates. If someone wants no prefix at all that can be accomplished by using an empty string for the setting.

**Comment by vsoch** [comment]
Perfect.
