### ISSUE TITLE
How to run binoc ?

### ISSUE THREAD

**Issue by muffato** [autamus/binoc#18]
Hello,
I'm trying to run `binoc` directly on a local _shpc_ registry from the command-line, but I can't find how to control the path to that registry. I'm trying something like this, as in README.md
``` 
$ BINOC_REPO_PATH=$PWD BINOC_PARSERS_LOADED=shpc BINOC_GIT_TOKEN=rEdAcTeD ./binoc 

 ____  _
| __ )(_)_ __   ___   ___
|  _ \| | '_ \ / _ \ / __|
| |_) | | | | | (_) | (__
|____/|_|_| |_|\___/ \___|
Application Version: develop

[Parsing Container Blueprints]
[Checking Containers for Updates]

[Scan Results]
0     Packages Parsed
0     Packages Updated
0     Packages Skipped
```

But, as you can see it cannot find any update.

The registry is a copy of https://github.com/singularityhub/singularity-hpc/tree/main/registry to `$PWD/registry`, where I have downgraded `redis`:
```diff
diff --git a/registry/redis/container.yaml b/registry/redis/container.yaml
index bbbb234..ddcd24e 100644
--- a/registry/redis/container.yaml
+++ b/registry/redis/container.yaml
@@ -4,14 +4,12 @@ maintainer: '@vsoch'
 description: Redis is an open-source, networked, in-memory, key-value data store with
   optional durability.
 latest:
-  7.0-rc: sha256:939f6b81ae093c4c58c3913d1c8b4d3e53910b7da6bd96e67a10136e037ad985
+  6.2.5: sha256:c98f0230b5f1831f4f5dd764c4ea8ef11d3e3a1a3593278eb952373d97c82b27
 tags:
   6.2.3-alpine: sha256:f8f0e809a4281714c33edf86f6da6cc2d4058c8549e44d8c83303c28b3123072
   6.2.4-alpine: sha256:0039796b887fd30e460353f14e46ba1004152aa97f5f59094cc21eac445fc89b
   6.2.5: sha256:c98f0230b5f1831f4f5dd764c4ea8ef11d3e3a1a3593278eb952373d97c82b27
-  6.2.6: sha256:0d9c9aed1eb385336db0bc9b976b6b49774aee3d2b9c2788a0d0d9e239986cb3
-  7.0-rc: sha256:939f6b81ae093c4c58c3913d1c8b4d3e53910b7da6bd96e67a10136e037ad985
-  latest: sha256:0d9c9aed1eb385336db0bc9b976b6b49774aee3d2b9c2788a0d0d9e239986cb3
+  latest: sha256:c98f0230b5f1831f4f5dd764c4ea8ef11d3e3a1a3593278eb952373d97c82b27
 aliases:
   redis-benchmark: /usr/local/bin/redis-benchmark
   redis-check-aof: /usr/local/bin/redis-check-aof
```

I've tried a few things for `BINOC_REPO_PATH`:
* omitting it: very quickly exits with no update found
* setting it to `/`: fails with `Error. repository does not exist`
* setting it to `$PWD`: runs for a while, then exits with no update found
* setting it to `$PWD/registry`: fails with `Error. repository does not exist`

Any tip would be appreciated 🙏🏼 

Regards,
Matthieu

**Comment by muffato** [comment]
OK, I think I'm getting there. It looks like `binoc` only works 1) if the current branch is named `main`, and 2) on `container.yaml` files that are present in the last commit, excluding the ones that have been locally deleted.

**Comment by alecbcs** [comment]
Hey @muffato! Do you have a copy of `binoc` in your SHPC repository? I'd try running it with something like this from the Binoc repository. It's admittedly been a couple of months since I've dived into this code but I'll check this out on a local shpc repository later today after a couple of meetings and see if I run into a similar error.

```
$ BINOC_REPO_PATH=/path/to/shpc BINOC_PARSERS_LOADED=shpc BINOC_GIT_TOKEN=rEdAcTeD go run binoc.go
```

**Comment by muffato** [comment]
Hi @alecbcs . Right: I had copied the registry to a local checkout of binoc, so that I could debug binoc at the same time. As far as I can see, `go run binoc.go` works the same as `./binoc`, and the constraints are on the repo:

1) `BINOC_REPO_PATH` must be a git repository. I guess that's because `binoc` is meant to be creating a pull-request.
2) the git repository has to be on the `main` branch, otherwise `binoc` fails with "reference not found"

In one occasion, `binoc` failed with "worktree contains unstaged changes", but I haven't been able to reproduce that.

Once I comply with those rules, I can run `binoc` fine.

**Comment by alecbcs** [comment]
We should fix this. Although Binoc was originally developed as a GitHub action if you're not generating a pull request with it we shouldn't require `BINOC_REPO_PATH` to be a git repository.

**Comment by muffato** [comment]
I managed to run binoc, so I'll close this issue, and open a new open about binoc requiring the directory to be a git checkout
