### ISSUE TITLE
Another use case for binoc!

### ISSUE THREAD

**Issue by vsoch** [autamus/binoc#2]
hey @alecbcs ! I think I have another potential use case for binoc! I started a fun project this weekend which is basically going to be a small local (filesystem) registry of singularity containers for users. The users will access them via lmod, and an admin will manage them via a small client. For the first shot, I'm just going to have admins add their own containers, e.g.,:

```bash
shpc add container.sif python/3.8 # and some way to make metadata)
```
and then users would do

```bash
module load python/3.8
```
And get an executable container on their path. But now I'm thinking it would be super cool to have, akin to spack, a folder with different configuration files that define pulls for containers. E.g.,

```bash
shpc install python/3.8
```
And that would have some configuration file for a python 3.8 container to pull, and whatever other LMOD file settings are needed.

For this use case, I'm thinking having a binoc in the repository to be able to check Docker (or other registry) images for new tags would be super useful! I'm thinking HPC admins would want some core set of containers for software, but then have some set of their "custom" research apps for users, so both a combination of local adds and installs would be good.

And here's another cool idea - imagine that this is linked to the autumus registry? That would have a clear path from:

```
spack package --> container --> something the user can directly used
```
I am thinking I'll add a spack namespace under the module path, like:

```bash
./modules/spack/python/3.8
```
and also ensure that the package versions are linked up with spack. So the key ingredient here would be having binoc be able to check for new tags. And the harder question would be, should we even consider latest? I was thinking no, because it's  a moving target. Let me know what you think! I started the project this morning and I'm really excited about the idea :)

**Comment by vsoch** [comment]
I guess there are two approaches:

 - have updates come from CI, so the admin just needs to pull to update the local repository
 - have any container accessible via the Docker API (e.g., I can test using an anonymous token to see https://ghcr.io/v2/autamus/python/tags/list).

**Comment by alecbcs** [comment]
Oooo @vsoch I like this idea! Using Singularity Containers first class citizens on HPCs!

No joke, I was just thinking about adding support for Docker Container tags Yesterday! Agreed about not using `latest` since it's a moving target. In the case that a container only utilizes `latest` though, what would you think about Binoc embedding a comment in the Dockerfile with the hash of the layer? We could then use that commented hash to determine when a newer hash is available?

**Comment by vsoch** [comment]
Let me think - so if binoc is just making a decision based on the static files in the repository, a comment (or label) that could be easily parsed would definitely work! 

If we have to determine it from the container itself, it would either need to look up the hash (in the manifest) and compare to a newly built image, or have the image with some annotation (assuming GitHub packages supports annotations) to get the comment.

My thinking is that the first case is easy and very reasonable to do.

**Comment by alecbcs** [comment]
Cool! I guess the first case works for Autamus, etc... where Binoc would be parsing a local file system of Dockerfiles. Do you anticipate wanting to use this system outside of a repository format? Where the user would just install/run Binoc and it should check with Singularity/Docker to see what container images are local and if they are up to date? If so maybe we should consider making a Singularity version of [Watchtower](https://github.com/containrrr/watchtower)?

**Comment by vsoch** [comment]
I'm wondering how generalized we can make this too. On the one extreme, we hard code this exact tool I'm making, and read a very specific config file for it (and this doesn't make sense to me) on the other extreme, we have a general config parser for a Dockerfile, and binoc doesn't care what you do with it (this is what I think makes sense - you could imagine many use cases beyond the one we are discussing).

So with this in mind, in terms of organization, I'm thinking that it would make sense to support an equivalent root in the binoc settings (the action). It's not technically a Dockerfile, but it is a configuration that supports updating some field with a docker tag. It's unlikely a user is going to have more than one kind of parser, so we can still use the default repo_path, but instead of spack, it would be something like docker-yaml (or docker-uri?)

```yaml
- name: Update Docker versions with binoc
  uses: autamus/binoc@v2.0.0
        with:
         ...
          repo_path: './containers'
          parsers_loaded: 'docker-yaml'
```
And then the structure under containers would have that same LMOD type structure, enforced by the user (and binoc). E.g.,:

```bash
./containers/
    python/
      3.8/
          container.yaml
```
And call the file whatever you please! Actually, we might not need the lmod structure here since it's just the config files to generate it. We could also do:

```bash
./containers/
    python/3.8.yaml
```
I think one directory would probably get unwieldy! And then the container.yaml or similar would have the container uri, latest tag, and any other metadata that seems necessary.

```yaml
docker: vanessa/salad
tag: latest # or probably not latest, but maybe could be?
maintainer: Vanessasaurus
```
And then binoc would look for a new tag, compare against the one in the yaml, and open a PR if a new one is available. But I'm wondering if we should follow the model of spack, and include all versions? That might be problematic with latest, but for others it would work, e.g.,

```yaml
docker: vanessa/salad
tags:
  - latest
  - 1.2
  - 1.3
maintainer: Vanessasaurus
```
It might even make sense to add a single "tag" parameter that binoc updates, so we don't have to worry about order of the yaml loading (assuming the top one is the most recently added):


```yaml
docker: vanessa/salad
latest: 2.3
tags:
  - 1.2
  - 2.3
  - 1.3
maintainer: Vanessasaurus
```

And just reading your comment! For parsing Dockerfiles, this would probably be a different use case, because would the user be interested in updating versions in the Dockerfiles? That could look like:
```yaml
- name: Update Docker versions with binoc
  uses: autamus/binoc@v2.0.0
        with:
         ...
          repo_path: './dockerfiles'
          parsers_loaded: 'dockerfile'
```
and then t

```bash
./dockerfiles/
    python/3.8/Dockerfile
```
And for that use case I'm wondering how we would store previous versions of the dockerfile, since you can't keep them in the same file like a package.py. Probably we'd have a different subfolder for each, and some metadata file to indicate latest (or a symbolic link from a latest tag to whatever it is).

Oh hmm watchtower looks interesting - it looks like it's intended to pull and then replace running containers with updated ones? Conceptually we want something similar, but much simpler - just an ability to always have a repository with updated container URIs. I think it's up to the linux admin to pull and then install. But then locally, I think for the tool I'm making we would want it to be easy to check for updates, but that's fairly trivial - something like:

```bash
shpc check python
==> You have python 3.7 installed, but the latest is 3.8. Would you like to install?
yes/no : yes
```
So arguably they could have an automated way to pull the updated repository, or down the line even have a set of configuration files from a separate repository (if they maintain it).

**Comment by vsoch** [comment]
And then just for a high level idea of how this folder of files will be used by singularity-hpc - there will be a default path in the repo for these recipes (and the user could add a custom one if they choose) and then let's say there is a python container config in that folder. Then the user would do:

```bash
shpc install python/3.8
```

Then the module would be generated and installed to the user's module folder (also customizable):

```bash
$install_dir/modules/
└── python
    └── 3.8/
        ├── module.lua
        └── python
```
and then the user (not the linux admin, the cluster user) would just be able to do:

```bash
module load python/3.8
```
And the container would be added to the path as python. So there is one potential issue - we need to figure out how to specify a custom entrypoint, either via the module file, or some other trick, because most of these containers might not execute and then hit the right executable.yyy

**Comment by alecbcs** [comment]
I'm so excited that we've gotten Binoc working with SHPC!!!

**Comment by vsoch** [comment]
Me too! I'll close the issue here after one final working test! And we can submit the little paper after that! :tada: And then back to debugging these spack builds for autamus :)

**Comment by vsoch** [comment]
I think we can close this!
